### ISSUE TITLE
Support asterisk in importFrom

### ISSUE THREAD

**Issue by ronilaukkarinen** [csstools/stylelint-value-no-unknown-custom-properties#11]
If `**/*.css` added to importFrom, we get following error:

![Screenshot](https://i.imgur.com/amoJXlY.png "Screenshot")

Full path works but have to be changed per project. Can asterisk be supported to enable stylelint-value-no-unknown-custom-properties from all subdirectories or their subdirectories recursively?

**Comment by diegocr** [comment]
If this is made, which i agree with, additionally implementing some kind of cache would be handy as well, so that we don't have to recursively traverse all directories nor reading from disk and parsing all the files every single time.

**Comment by romainmenke** [comment]
This is beyond the scope of this plugin.

We feel that the number of files that should be listed in `importFrom` and how much this config changes is limited compared to the maintenance burden glob file lookups.
