### ISSUE TITLE
Imports aren't relative (doesn't work with WebStorm)

### ISSUE THREAD

**Issue by davidgilbertson** [csstools/stylelint-value-no-unknown-custom-properties#16]
You're [using `path.resolve()` to find files](https://github.com/csstools/stylelint-value-no-unknown-custom-properties/blob/98f85f6fef1cf811f2f362f4a9a4622c5951f62b/src/lib/get-custom-properties-from-imports.js#L67), which defaults to using the [current working directory](https://nodejs.org/api/path.html#path_path_resolve_paths).

I guess with WebStorm, which has Stylelint support built in, the 'current working directory' is the CSS file.

So when I define the path `src\styles\colors.css` for this rule, and view a file in the directory `src\components\Button`, I get the error:

```
Error: ENOENT: no such file or directory, open '...my-app\src\components\Button\src\styles\colors.css
```

Not exactly a fault of your plugin, so happy for you to close this (although if you wanted to be awesome, this plugin would treat paths as being **relative to the config file**).

The workaround (for future travellers) is to use a JS module for stylelint config and make sure that the paths passed to this plugin are absolute.

```js
// stylelint.config.js
const path = require('path');

module.exports = {
  plugins: ['stylelint-value-no-unknown-custom-properties'],
  rules: {
    'csstools/value-no-unknown-custom-properties': [
      true,
      {
        importFrom: [
          path.resolve(__dirname, 'src/file1.css'),
          path.resolve(__dirname, 'src/file2.css'),
        ],
      },
    ],
  },
};
```

**Comment by romainmenke** [comment]
I think your workaround is actually the best practice.
I don't think we need to change anything in the code :)
