### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by edoardocavazza** [csstools/stylelint-value-no-unknown-custom-properties#17]
I can not see any release after this merge: https://github.com/csstools/stylelint-value-no-unknown-custom-properties/pull/9. Is there any issue with that?

**Comment by ronilaukkarinen** [comment]
It seems this project is not active.

Please see my working fork you can use (as stated [here](https://github.com/csstools/stylelint-value-no-unknown-custom-properties/pull/21#issuecomment-1064057536), got tired of waiting for the maintainer to merge my PR):

```bash
npm install @ronilaukkarinen/stylelint-value-no-unknown-custom-properties --save-dev
```

I'm going to keep it updated as we use this package in our daily life at work.

**Comment by Antonio-Laguna** [comment]
A new release has just happened for anyone following this issue. 4.0.0 is out!
