### ISSUE TITLE
Consider adding rule to Stylelint

### ISSUE THREAD

**Issue by jameschensmith** [csstools/stylelint-value-no-unknown-custom-properties#28]
Thoughts / opinions on whether this rule should be graduated to a built-in Stylelint rule? I've been thinking about this since I found this rule after observing GitLab's interest in using it. I'm not sure if Stylelint would accept the rule into their built-in rules, as this rule is on the larger side when comparing with their other rules, but I think it's worth reaching out to them to get their thoughts. I've listed some grouped thoughts below.

If anything, this issue can also be seen as a list of potential improvements to the rule :slightly_smiling_face: 

**Reasons for adding rule to Stylelint**

-  CSS Tools maintainers can focus on [postcss-plugins](https://github.com/csstools/postcss-plugins) & [cssdb](https://github.com/csstools/cssdb).
- Package has ~9,382 average weekly downloads. This is one of the top Stylelint community plugins / rules.
- As a built-in rule, `value-no-unknown-custom-properties` (`value-no-unknown-custom-property`?) will **(1)** reach a larger audience, **(2)** gain regular maintenance along with other built-in rules, **(3)** take advantage of some of the built-in rules' shared utilities, **(4)** potentially gain performance / consistency improvements with rule being consistently tested in their CI, and **(5)** potentially gain more support for custom syntaxes which use custom properties.

**Drawbacks for adding rule to Stylelint**

- Stylelint has [not moved to ESM yet](https://github.com/stylelint/stylelint/issues/5291). Since this package has already moved to ESM, users of the library might not like the experience switching to the built-in rule. This may not be a problem if they are already using the built-in rules, though.

**Action items before rule is ready to be added**

Items are non-exhaustive, and open to changes requested. They are items I can initially find which makes this codebase closer to a built-in rule.

- [ ] Format codebase using `@stylelint/prettier-config`.
- [ ] Lint codebase using `eslint-config-stylelint`.
- [ ] Lint JS types using TypeScript.
- [ ] Remove Rollup in favor of no bundler.
- [ ] Migrate from ESM to CommonJS module system.
- [ ] Move around JS files to similar architecture of Stylelint rules.
- [ ] Bring most of the files (rule name, messages, etc.) back into `index.js`.

**Comment by jameschensmith** [comment]
@Antonio-Laguna, what are your thoughts on this? If you are interested, I can start working on this right away and also submit an issue with Stylelint to get their thoughts on this. Let me know when you get a chance. Thanks!

**Comment by Antonio-Laguna** [comment]
@jameschensmith I'm maintaining these repos to the best of my ability (and my time) but I'm not an owner of the code so I could not take this step from my side. 

That said I also doubt that they'd consider such an addition given that the rule is somewhat convoluted and needs some processing which they're always trying to avoid. You can look at the deprecation of `function-calc-no-invalid`. 

Furthermore, my point was that no active development is being done on this plugin (or any out of those you mentioned) but that doesn't mean that it's not going to be updated anymore but rather that it's considered as dev completed and it's kept updated to be used with latest stylelint.

I'm not a heavy user of this rule myself but we can also consider adding new features such as #20

**Comment by jameschensmith** [comment]
@Antonio-Laguna, you are doing a great job with maintaining these repositories. I hope that you don't take this suggestion as me discrediting that, because I don't discredit that at all. That makes sense that you aren't able to make this decision. It sounds like approval would need to come from @jonathantneal.

Upon looking into `function-calc-no-invalid`, it seems like that rule was quite a bit larger in comparison. I see 130k (kb?) size vs this rule's 32kb size. In terms of processing, there are some built-in rules which already use `postcss-value-parser`. Still, I agree that some additional processing is involved when traversing imports.

The state of the project being dev completed makes sense. My list of potential improvements was not intended to be active development, but rather maintenance work to model Stylelint's rules / architecture. If this rule is not being added to Stylelint, though, I understand how there would be no need to do those improvements.

I appreciate your thoughts! They are very helpful in getting an understanding of the direction for this project :blush: :+1:

**Comment by Antonio-Laguna** [comment]
@jameschensmith not taking that personally :) 

I wasn't trying to compare that in terms of size but in terms of complexity. From what I can see, `stylelint` only adds features that have to do with CSS language itself but this enters the realm of plugins and extensions.

This is as if you'd ask us to take care of https://github.com/MadLittleMods/postcss-css-variables, this deviates from our purpose with the plugins we maintain as it's not spec compliant.

> The state of the project being dev completed makes sense. My list of potential improvements was not intended to be active development, but rather maintenance work to model Stylelint's rules / architecture. 

Completely understood this part from the beginning :) I was trying to explain that one of the reasons this is not being actively developed is because there's probably no need for any new feature but I'm happy to stand corrected and evaluate features ;)

**Comment by silverwind** [comment]
Tracked in https://github.com/stylelint/stylelint/issues/6361.

**Comment by romainmenke** [comment]
see : https://stylelint.io/user-guide/rules/no-unknown-custom-properties
