### ISSUE TITLE
Support for "importFrom"  .less and .scss files

### ISSUE THREAD

**Issue by DevYimo** [csstools/stylelint-value-no-unknown-custom-properties#31]
Hi!
Would be possible to add support for styles from `.less & .scss` files?

We directly use ` .less` styles, but for Theme support, we decided to use css var(--xxx).
 - For now it is not blocker to use theme.css for us, because we have every "var" style in only one file (without any less things), but in the future?
 
 Thanks!

**Comment by romainmenke** [comment]
It isn't possible to load `.less` and `.scss` files that are actual Less and SCSS.
This rule doesn't know how to parse and interpret those languages.

If you are writing pure CSS in such files you should just use `.css` as the file extension.

**Comment by wolfitoXtreme** [comment]
Adding this caveat to the readme will benefit people a lot,  so, given the premise they are using SCSS or LESS (which a standard nowadays) they would not venture into installing and trying to configure this plugin. Thanks.

**Comment by romainmenke** [comment]
SCSS and LESS are not standard at all.
Otherwise they would be plain CSS ;)

-----

PR's are welcome
