### ISSUE TITLE
Stylelint v15

### ISSUE THREAD

**Issue by DevYimo** [csstools/stylelint-value-no-unknown-custom-properties#32]
Hi,
Would be possible to add support for stylelint  v15+ ?

Thank you!

**Comment by silverwind** [comment]
Plugin seems to work on a basic level on Stylelint 15, so maybe this is just a simple bump in [`peerDependencies`](https://github.com/csstools/stylelint-value-no-unknown-custom-properties/blob/3cd55721a3783169e029de361101e0e085b44a82/package.json#L53).

**Comment by alex-e-leon** [comment]
I've submitted a pull request ^

**Comment by liyokuna** [comment]
hello, 

any news, i ain't see that merge.

**Comment by liyokuna** [comment]
hello
any news ?!

**Comment by johanneswilm** [comment]
@jameschensmith @Antonio-Laguna Any chance you could review this very minimal PR? It's a major blocker for a lot of projects.

**Comment by Antonio-Laguna** [comment]
@johanneswilm thanks for the ping. I forgot completely about this (despite @alex-e-leon ping!) This is now available as 5.0.0

**Comment by johanneswilm** [comment]
thanks @Antonio-Laguna !
