### ISSUE TITLE
importFrom HTML

### ISSUE THREAD

**Issue by silverwind** [csstools/stylelint-value-no-unknown-custom-properties#33]
I use a pattern where CSS vars are declared in a `<style>` tag in HTML to ensure they are available in all imported CSS files. Would be nice if this plugin could offer a way to read the vars from HTML:

````html
<html>
  <head>
    <style>
      :root {
        --color-red: #dd2222;
      }
    </style>
  </head>
<html>
````

**Comment by silverwind** [comment]
I suppose it may be possible if the plugin could just "see" all files that stylelint sees. I lint HTML inline CSS via this stylelint config:

````yaml
overrides:
  - files: ["**/*.html"]
    customSyntax: postcss-html
````

So if the plugin can "see" all files in the lint, an option like `importFrom` may be unnecessary, but I think it may require an architectural change in stylelint for such true multi-file support.

**Comment by silverwind** [comment]
Also see discussion https://github.com/stylelint/stylelint/issues/6361.

**Comment by romainmenke** [comment]
I think this is beyond the scope of this rule.

You might get creative with `importFrom` as you can load JavaScript files here.
Such a JavaScript file might do all the html parsing and expose the results as an object of key/values.
