### ISSUE TITLE
Support for import notation "url" 

### ISSUE THREAD

**Issue by kazukitaninaka** [csstools/stylelint-value-no-unknown-custom-properties#37]
Hi!

It would be great if this package can have a support for `import-notation: "url"` !
Currently it cannot properly parse the following import notation 
```
@import url("foo.css");
```
even though the URL notation is the default configuration in `stylelint-config-standard`.
ref: https://github.com/stylelint/stylelint-config-standard/blob/59f350d74df3665f50c19cd73b725d301b742413/index.js#L68C3-L68C3

Thanks a lot!

**Comment by romainmenke** [comment]
This has been fixed, thank you for reporting
