### ISSUE TITLE
ESM support

### ISSUE THREAD

**Issue by Geloosa** [csstools/stylelint-value-no-unknown-custom-properties#39]
Please, add ESM support to be able to migrate to Stylelint 16 https://stylelint.io/migration-guide/to-16/

**Comment by juliuxu** [comment]
This [package already support esm](https://github.com/csstools/stylelint-value-no-unknown-custom-properties/blob/main/package.json#L11-L18), but stylelint tries to import it as cjs when the plugin is specified as a string.

We solved this by manually importing this plugin and pasting it into the `plugins` option

<img width="1006" alt="image" src="https://github.com/csstools/stylelint-value-no-unknown-custom-properties/assets/244257/cfe5809f-89e3-48bf-9d15-95055ea303db">
