### ISSUE TITLE
importFrom function

### ISSUE THREAD

**Issue by privatenumber** [csstools/stylelint-value-no-unknown-custom-properties#4]
In my codebase, we have multiple vars files and not all of them are imported in every consuming file.

I'd like to request that the `importFrom` supports a function so that the `@imports` can be resolved to provide the appropriate variables per file.

**Comment by romainmenke** [comment]
I think this is beyond the scope of this plugin but I will keep this request in mind for the Stylelint core rule : https://stylelint.io/user-guide/rules/no-unknown-custom-properties

We are working on an analogue for `importFrom` for core rules.
