### ISSUE TITLE
Resolve `importFrom` relative to config file, not working directory

### ISSUE THREAD

**Issue by silverwind** [csstools/stylelint-value-no-unknown-custom-properties#41]
In a monorepo with a `.stylelintrc.yaml` in a subdirectory I'm getting errors from my [editor integration](https://github.com/sublimelsp/LSP-stylelint) because this plugin resolves files relative to working directory instead of relative to the config file. I'd suggest to always resolve paths relative to the config file. This is how pretty much all other linters work too.

In case this suggestion is not possible, you could introduce a `<rootDir>` option like `jest` also has, e.g. `<rootDir>/style.css` to specify the path relative to the config file.

**Comment by romainmenke** [comment]
Better to solve this after there is a "core" solution.

See : https://github.com/stylelint/stylelint/issues/4088

**Comment by silverwind** [comment]
Yes indeed. But until then, this nice plugin is unusable for me 😢. If stylelint plugins have access to the config file path where the plugin's options are set, it shouldn't be too hard of a feature to add.

**Comment by romainmenke** [comment]
PR's are welcome :)

**Comment by silverwind** [comment]
I guess I will go another route and just pass absolute paths to the plugin. This means I have to migrate my config from yaml to js, but that will be worth it anyways.
