### ISSUE TITLE
Publish v3.0.0 to npm

### ISSUE THREAD

**Issue by pirelenito** [csstools/stylelint-value-no-unknown-custom-properties#7]
Thanks for the amazing library ❤️

I noticed you recently bumped the version to 3.0.0. Are there any plans on publishing this new version to npm?

I'm particular interested in the `peedDependency` change. 

Cheers!

**Comment by hmsk** [comment]
@jonathantneal How can I help you to release/maintain? I can work on that if you add me to the collaborators of this repo and npm (As [hmsk](https://www.npmjs.com/~hmsk) as well).

**Comment by jonathantneal** [comment]
One of the changes I just made was to the CHANGELOG.md. It was updated from "May 12, 2018" to "May 12, 2020". 😱

The release is now published. I am very sorry, and quite embarrassed.

However, 3.0.0 is now published! 🎉
